# These variables should match those in lib/stacks/pan_american_of_the_day_stack.ts
UBI_AUTH = "UBI_AUTH"
EVENT_NAME = "EVENT_NAME"
EVENT_CLUB_ID = "EVENT_CLUB_ID"
MAPS_CLUB_ID = "MAPS_CLUB_ID"
CAMPAIGN_ID = "CAMPAIGN_ID"
STORAGE_BUCKET_NAME = "STORAGE_BUCKET_NAME"
SECRETS_BUCKET_NAME = "SECRETS_BUCKET_NAME"
